library(Biobase)
library(breastCancerNKI)
data(nki)
dir.create("nki")
write.table(exprs(nki), file="nki/NKI.exprs.txt",sep="\t",quote=FALSE)
write.table(pData(nki), file="nki/NKI.pData.txt",sep="\t",quote=FALSE)
write.table(fData(nki), file="nki/NKI.fData.txt",sep="\t",quote=FALSE)

datadir <- system.file("extdata", package="estrogen")
dir.create("estrogen")
sapply(list.files(datadir), function(x) file.copy(paste(datadir,x,sep="/"),"estrogen"))